---
- name: Check that required volumes are present
  docker_volume:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx_conf
    - nginx_html
    - nginx_vhost
    - docker_gen_templates
    - proxy_certs

- name: Add nginx.tmpl to docker_gen_templates volume
  template:
    src: nginx.tmpl.j2
    dest: /var/lib/docker/volumes/docker_gen_templates/_data/nginx.tmpl
    variable_start_string: '[%'
    variable_end_string: '%]'
  become: yes

- name: Restart nginx container
  docker_container:
    name: nginx
    image: nginx
    state: started
    restart: yes
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_html:/usr/share/nginx/html
      - nginx_vhost:/etc/nginx/vhost.d
      - proxy_certs:/etc/nginx/certs:ro

- name: Restart nginx-gen container
  docker_container:
    name: nginx-gen
    image: jwilder/docker-gen
    state: started
    restart: yes
    volumes:
      - docker_gen_templates:/etc/docker-gen/templates:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_conf:/etc/nginx/conf.d
      - nginx_html:/usr/share/nginx/html
      - nginx_vhost:/etc/nginx/vhost.d
      - proxy_certs:/etc/nginx/certs:ro
    entrypoint: ["/usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"]

- name: Restart letsencrypt-nginx-proxy-companion container
  docker_container:
    name: letsencrypt-nginx-proxy-companion
    image: jrcs/letsencrypt-nginx-proxy-companion:stable
    state: started
    restart: yes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_conf:/etc/nginx/conf.d
      - nginx_html:/usr/share/nginx/html
      - nginx_vhost:/etc/nginx/vhost.d
      - proxy_certs:/etc/nginx/certs:rw
    env:
        NGINX_DOCKER_GEN_CONTAINER: nginx-gen
