---
- src: https://github.com/Fongshway/ansible-archlinux_aur.git
  name: fongshway.aur

- src: https://github.com/Fongshway/ansible-role-ssh-user.git
  name: fongshway.ssh_user

- src: https://github.com/Fongshway/ansible-role-zsh.git
  name: fongshway.zsh
