---
- name: Install pip with pacman
  pacman: name={{ item }} state=present
  with_items:
    - python-pip
    - python2-pip
  when: ansible_os_family == 'Arch Linux'

- name: Install virtualenv with pacman
  pacman: name={{ item }} state=present
  with_items:
    - python-virtualenv
    - python2-virtualenv
  when: ansible_os_family == 'Arch Linux'
