---
- name: Create primary unprivileged user account
  user:
    name: "{{ common_user }}"
    password: "{{ user_password }}"
    group: users
    groups: wheel
    append: yes
    shell: /bin/zsh
    generate_ssh_key: yes
  become: true
