---
- name: Check if initialization has been done
  stat: path={{ ansible_env.HOME }}/.initialized_system
  register: initialized_system

# The equivalent of "pacman -Syu"
- name: First time pacman upgrade
  pacman: update_cache=yes upgrade=yes
  become: true
  when: not initialized_system.stat.exists

# The equivalent of "pacman -S base-devel"
- name: Ensure pacman base-devel packages are present
  pacman: name=base-devel state=present
  when: not initialized_system.stat.exists

- import_tasks: hosts.yaml
  when: not initialized_system.stat.exists

- import_tasks: timezone.yaml
  when: not initialized_system.stat.exists

- import_tasks: sudoers.yaml
  when: not initialized_system.stat.exists

- name: Create /root/.initialized_system lock file
  file:
    path: "{{ ansible_env.HOME }}/.initialized_system"
    state: touch
  become: true
  when: not initialized_system.stat.exists
