---
- name: laptop.yaml
  hosts: local
  roles:
    - {role: system_init,         tags: ["system_init",     "init"]}
    - {role: package_install,     tags: ["package_install", "init"]}
    - {role: fongshway.user,      tags: ["user",            "init"]}
    - {role: python,              tags: ["python"]}
    - {role: dotfiles,            tags: ["dotfiles"]}
    - {role: fongshway.aur,       tags: ["aur"]}
    - {role: tmux,                tags: ["tmux"]}
    - {role: fzf,                 tags: ["fzf"]}
  vars_files:
    - ../group_vars/laptop/common.yaml
    - ../group_vars/laptop/fongshway.aur.yaml
    - ../group_vars/laptop/fongshway.user.yaml
    - ../group_vars/laptop/fongshway.zsh.yaml
    - ../group_vars/laptop/package_install.yaml
    - ../group_vars/laptop/system_init.yaml
    - ../group_vars/laptop/vault.yaml
