---
- name: linode.yaml
  hosts: linode
  roles:
    - {role: system_init,         tags: ["system_init",     "init"]}
    - {role: package_install,     tags: ["package_install", "init"]}
    - {role: fongshway.ssh_user,  tags: ["ssh_user",        "init"]}
    - {role: sshd,                tags: ["sshd",            "init"]}
    - {role: python,              tags: ["python"]}
    - {role: fongshway.zsh,       tags: ["zsh"]}
    - {role: fongshway.aur,       tags: ["aur"]}
    - {role: taskd,               tags: ["taskd"]}
    - {role: tmux,                tags: ["tmux"]}
    - {role: fzf,                 tags: ["fzf"]}
    - {role: docker_jenkins,      tags: ["docker", "jenkins"]}
    - {role: docker_portainer,    tags: ["docker", "portainer"]}
    - {role: docker_nginx,        tags: ["docker", "nginx"]}
  vars_files:
    - ../group_vars/linode/common.yaml
    - ../group_vars/linode/docker_jenkins.yaml
    - ../group_vars/linode/docker_portainer.yaml
    - ../group_vars/linode/fongshway.aur.yaml
    - ../group_vars/linode/fongshway.ssh_user.yaml
    - ../group_vars/linode/fongshway.zsh.yaml
    - ../group_vars/linode/package_install.yaml
    - ../group_vars/linode/system_init.yaml
    - ../group_vars/linode/taskd.yaml
    - ../group_vars/linode/vault.yaml
