---
- name: linode.yaml
  hosts: linode
  roles:
    - {role: system_init,         tags: ["system_init",     "init"]}
    - {role: package_install,     tags: ["package_install", "init"]}
    - {role: user,                tags: ["user",            "init"]}
    - {role: ssh,                 tags: ["ssh",             "init"]} # Depends on user role running first
    - {role: python,              tags: ["python"]}
    - {role: fongshway.oh-my-zsh, tags: ["zsh"]}
    - {role: fongshway.aur,       tags: ["aur"]}
    - {role: taskd,               tags: ["taskd"]}
    - {role: tmux,                tags: ["tmux"]}
    - {role: vcsh,                tags: ["vcsh"]}
    - {role: fzf,                 tags: ["fzf"]}
  vars_files:
    - ../group_vars/linode/common.yaml
    - ../group_vars/linode/fongshway.aur.yaml
    - ../group_vars/linode/fongshway.oh-my-zsh.yaml
    - ../group_vars/linode/package_install.yaml
    - ../group_vars/linode/ssh.yaml
    - ../group_vars/linode/system_init.yaml
    - ../group_vars/linode/taskd.yaml
    - ../group_vars/linode/user.yaml
    - ../group_vars/linode/vault.yaml
