---
- name: First time pacman upgrade (i.e. pacman -Syu)
  pacman:
    update_cache: yes
    upgrade: yes
  become: true

- name: Install packages
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - base-devel
    - dbus
    - inetutils
