---
- name: Install tmux with pacman
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - tmux
    - ruby
  become: true
  when: ansible_os_family == 'Arch Linux'

- name: Checkout tmux-better-mouse-mode from Github
  git:
    repo: https://github.com/NHDaly/tmux-better-mouse-mode
    dest: "{{ ansible_env.HOME }}/.config/tmux/tmux-scroll-copy-mode"
    update: no

- name: Install tmuxinator with gem
  gem:
    name: tmuxinator
    state: present
    user_install: no
  become: true